USE #:DB_NAME:#;
GO

EXEC sys.sp_cdc_disable_db;
GO

USE [master];
ALTER DATABASE [#:DB_NAME:#] SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE [#:DB_NAME:#] SET ONLINE;
DROP DATABASE #:DB_NAME:#;

